package setup

import (
	"context"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"sync"
	"time"

	"github.com/testcontainers/testcontainers-go"
	"gopkg.in/yaml.v3"

	"go-clean-api-scaffold/internal/config"
)

type setup struct {
	ctx        context.Context
	config     *config.Config
	containers map[string]testcontainers.Container
}

func NewSetup(config *config.Config) *setup {
	config.Server.Port = config.Test.Server.Port

	return &setup{
		ctx:        context.Background(),
		config:     config,
		containers: make(map[string]testcontainers.Container),
	}
}

func (s *setup) writeTestConfig() error {
	file, err := os.OpenFile("config_test.yaml", os.O_RDWR|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return err
	}
	defer file.Close()
	if _, err := file.WriteString("# This file is generated by test script, do not edit\n"); err != nil {
		return err
	}

	enc := yaml.NewEncoder(file)
	if err := enc.Encode(s.config); err != nil {
		return err
	}

	return nil
}

func (s *setup) setupSqlite() error {
	wd, err := os.Getwd()
	if err != nil {
		return err
	}
	abs := filepath.Join(wd, "test.db")
	s.config.Database.Sqlite.Path = abs
	return nil
}

func (s *setup) SetupInfrastructure() error {
	fmt.Println("Setting up feature test infrastructure...")
	if err := s.setupSqlite(); err != nil {
		return err
	}

	if err := s.writeTestConfig(); err != nil {
		return err
	}

	go s.setupServer()

	return s.waitForServer()
}

func (s *setup) waitForServer() error {
	address := "localhost:" + strconv.Itoa(s.config.Server.Port)
	deadline := time.Now().Add(5 * time.Second)
	var lastErr error

	for time.Now().Before(deadline) {
		conn, err := net.DialTimeout("tcp", address, 100*time.Millisecond)
		if err == nil {
			_ = conn.Close()
			return nil
		}

		lastErr = err
		time.Sleep(100 * time.Millisecond)
	}

	return fmt.Errorf("server did not start on %s: %w", address, lastErr)
}

func (s *setup) TerminateInfrastructure() {
	fmt.Println("Terminating feature test infrastructure...")

	wg := &sync.WaitGroup{}
	for name, container := range s.containers {
		wg.Add(1)
		go func(name string, container testcontainers.Container) {
			defer wg.Done()
			fmt.Println("Terminating container:", name)
			if err := container.Terminate(s.ctx); err != nil {
				fmt.Println("Failed to terminate container:", name, err)
			}
		}(name, container)
	}

	wg.Wait()
	fmt.Println("Feature test infrastructure terminated.")
}
